import type {
  RestaurantWithStatus,
  MenuCategoryWithItems,
  RestaurantHours,
} from "@rwc/shared";

// Mock restaurant data from real RWC restaurant profiles
// Used for development before Supabase is connected

const mockHours = (closedDay?: number): RestaurantHours[] => {
  const days = [0, 1, 2, 3, 4, 5, 6];
  return days
    .filter((d) => d !== closedDay)
    .map((d) => ({
      id: `hours-${d}`,
      restaurant_id: "",
      day_of_week: d,
      open_time: "11:00",
      close_time: "21:00",
      closes_next_day: false,
    }));
};

export function getMockRestaurants(): RestaurantWithStatus[] {
  const now = new Date();
  const currentHour = now.getHours();
  const isLunchOrDinner = currentHour >= 11 && currentHour < 21;

  return [
    {
      id: "r1",
      slug: "la-viga",
      name: "La Viga Seafood & Cocina Mexicana",
      description:
        "Named after La Viga, Mexico City's massive seafood market. Coastal Mexican flavors with modern California touches.",
      cuisine_tags: ["Mexican", "Seafood"],
      address: "1772 Broadway",
      city: "Redwood City",
      state: "CA",
      zip: "94063",
      phone: "(650) 679-8141",
      lat: 37.4863,
      lng: -122.2275,
      rating: 4.2,
      review_count: 2008,
      price_range: "$$",
      is_active: true,
      default_prep_time_min: 30,
      stripe_account_id: null,
      image_url: null,
      created_at: "",
      is_open: isLunchOrDinner,
      hours: mockHours(),
    },
    {
      id: "r2",
      slug: "mazra",
      name: "MAZRA",
      description:
        "Authentic Levantine and Mediterranean dishes prepared over 100% mesquite wood fire. Tapas-style, vibrant, meant to be shared.",
      cuisine_tags: ["Mediterranean", "BBQ"],
      address: "2021 Broadway Street",
      city: "Redwood City",
      state: "CA",
      zip: "94063",
      phone: "(650) 503-8440",
      lat: 37.4879,
      lng: -122.2297,
      rating: 4.5,
      review_count: 1043,
      price_range: "$$",
      is_active: true,
      default_prep_time_min: 25,
      stripe_account_id: null,
      image_url: null,
      created_at: "",
      is_open: isLunchOrDinner && now.getDay() !== 1,
      hours: mockHours(1), // Closed Monday
    },
    {
      id: "r3",
      slug: "nomadic-kitchen",
      name: "Nomadic Kitchen",
      description:
        "Turkish cuisine with the highest Yelp rating in Redwood City. Authentic flavors from Istanbul to your table.",
      cuisine_tags: ["Turkish", "Mediterranean"],
      address: "2086 Broadway",
      city: "Redwood City",
      state: "CA",
      zip: "94063",
      phone: "(650) 556-9999",
      lat: 37.4882,
      lng: -122.2301,
      rating: 4.9,
      review_count: 240,
      price_range: "$$",
      is_active: true,
      default_prep_time_min: 25,
      stripe_account_id: null,
      image_url: null,
      created_at: "",
      is_open: isLunchOrDinner,
      hours: mockHours(),
    },
    {
      id: "r4",
      slug: "vesta",
      name: "Vesta",
      description:
        "Handcrafted wood-fired pizzas and dynamic small plates since 2012. Quirky Neapolitan pizzas with California-influenced toppings.",
      cuisine_tags: ["Pizza", "Italian"],
      address: "2022 Broadway",
      city: "Redwood City",
      state: "CA",
      zip: "94063",
      phone: "(650) 362-5052",
      lat: 37.4878,
      lng: -122.2296,
      rating: 4.5,
      review_count: 2611,
      price_range: "$$",
      is_active: true,
      default_prep_time_min: 20,
      stripe_account_id: null,
      image_url: null,
      created_at: "",
      is_open: isLunchOrDinner && now.getDay() !== 0,
      hours: mockHours(0), // Closed Sunday
    },
    {
      id: "r5",
      slug: "timber-and-salt",
      name: "Timber & Salt",
      description:
        "New American steaks and craft cocktails in an upscale yet approachable setting on Middlefield Road.",
      cuisine_tags: ["American", "Steaks"],
      address: "881 Middlefield Road",
      city: "Redwood City",
      state: "CA",
      zip: "94063",
      phone: "(650) 367-2300",
      lat: 37.4815,
      lng: -122.2321,
      rating: 4.5,
      review_count: 536,
      price_range: "$$$",
      is_active: true,
      default_prep_time_min: 35,
      stripe_account_id: null,
      image_url: null,
      created_at: "",
      is_open: isLunchOrDinner,
      hours: mockHours(),
    },
    {
      id: "r6",
      slug: "donato-enoteca",
      name: "Donato Enoteca",
      description:
        "Modern Italian wine bar and restaurant featuring handmade pastas, wood-fired dishes, and an extensive Italian wine list.",
      cuisine_tags: ["Italian", "Wine Bar"],
      address: "1041 Middlefield Road",
      city: "Redwood City",
      state: "CA",
      zip: "94063",
      phone: "(650) 701-1000",
      lat: 37.4826,
      lng: -122.2328,
      rating: 3.8,
      review_count: 1107,
      price_range: "$$-$$$",
      is_active: true,
      default_prep_time_min: 30,
      stripe_account_id: null,
      image_url: null,
      created_at: "",
      is_open: isLunchOrDinner,
      hours: mockHours(),
    },
    {
      id: "r7",
      slug: "angelicas",
      name: "Angelicas",
      description:
        "California-Latin fusion on Main Street. Vibrant flavors, fresh ingredients, and creative cocktails in a lively atmosphere.",
      cuisine_tags: ["California", "Latin"],
      address: "863 Main Street",
      city: "Redwood City",
      state: "CA",
      zip: "94063",
      phone: "(650) 365-3226",
      lat: 37.4845,
      lng: -122.2299,
      rating: 4.2,
      review_count: 1395,
      price_range: "$$-$$$",
      is_active: true,
      default_prep_time_min: 30,
      stripe_account_id: null,
      image_url: null,
      created_at: "",
      is_open: isLunchOrDinner,
      hours: mockHours(),
    },
    {
      id: "r8",
      slug: "broadway-masala",
      name: "Broadway Masala",
      description:
        "Regional Indian cuisine recognized by the Michelin Guide four times. Authentic spices and traditional recipes.",
      cuisine_tags: ["Indian"],
      address: "2397 Broadway",
      city: "Redwood City",
      state: "CA",
      zip: "94063",
      phone: "(650) 369-9000",
      lat: 37.4897,
      lng: -122.2324,
      rating: 4.3,
      review_count: 1112,
      price_range: "$$",
      is_active: true,
      default_prep_time_min: 25,
      stripe_account_id: null,
      image_url: null,
      created_at: "",
      is_open: isLunchOrDinner,
      hours: mockHours(),
    },
    {
      id: "r9",
      slug: "hurrica",
      name: "Hurrica",
      description:
        "Seafood and live-fire cooking on the waterfront. TripAdvisor #1 in Redwood City, top 1% worldwide.",
      cuisine_tags: ["Seafood", "American"],
      address: "150 Northpoint Court",
      city: "Redwood City",
      state: "CA",
      zip: "94063",
      phone: "(650) 482-4000",
      lat: 37.4960,
      lng: -122.2280,
      rating: 4.4,
      review_count: 524,
      price_range: "$$$",
      is_active: true,
      default_prep_time_min: 35,
      stripe_account_id: null,
      image_url: null,
      created_at: "",
      is_open: isLunchOrDinner,
      hours: mockHours(),
    },
    {
      id: "r10",
      slug: "pamilya",
      name: "Pamilya",
      description:
        "Authentic Filipino cuisine bringing family recipes to Redwood City. Comforting, flavorful dishes from the Philippines.",
      cuisine_tags: ["Filipino"],
      address: "756 Woodside Road",
      city: "Redwood City",
      state: "CA",
      zip: "94061",
      phone: "(650) 260-8999",
      lat: 37.4605,
      lng: -122.2349,
      rating: 4.5,
      review_count: 119,
      price_range: "$$",
      is_active: true,
      default_prep_time_min: 25,
      stripe_account_id: null,
      image_url: null,
      created_at: "",
      is_open: isLunchOrDinner,
      hours: mockHours(),
    },
    {
      id: "r11",
      slug: "la-fonda",
      name: "La Fonda",
      description:
        "Mexico City-style Mexican cuisine. Traditional family recipes with authentic flavors from the capital.",
      cuisine_tags: ["Mexican"],
      address: "820 Veterans Blvd",
      city: "Redwood City",
      state: "CA",
      zip: "94063",
      phone: "(650) 364-1233",
      lat: 37.4790,
      lng: -122.2195,
      rating: 4.5,
      review_count: 323,
      price_range: "$$",
      is_active: true,
      default_prep_time_min: 25,
      stripe_account_id: null,
      image_url: null,
      created_at: "",
      is_open: isLunchOrDinner,
      hours: mockHours(),
    },
    {
      id: "r12",
      slug: "pizzeria-cardamomo",
      name: "Pizzeria Cardamomo",
      description:
        "Neapolitan-style Italian pizza and pasta on Broadway. Traditional recipes with a modern touch.",
      cuisine_tags: ["Italian", "Pizza"],
      address: "2053A Broadway",
      city: "Redwood City",
      state: "CA",
      zip: "94063",
      phone: "(650) 482-4545",
      lat: 37.4880,
      lng: -122.2298,
      rating: 4.5,
      review_count: 239,
      price_range: "$$",
      is_active: true,
      default_prep_time_min: 20,
      stripe_account_id: null,
      image_url: null,
      created_at: "",
      is_open: isLunchOrDinner,
      hours: mockHours(),
    },
    {
      id: "r13",
      slug: "mistral",
      name: "Mistral",
      description:
        "New American waterfront fine dining with stunning views. Seasonal menus celebrating Bay Area ingredients.",
      cuisine_tags: ["American", "Fine Dining"],
      address: "370 Bridge Parkway",
      city: "Redwood City",
      state: "CA",
      zip: "94065",
      phone: "(650) 802-9222",
      lat: 37.5020,
      lng: -122.2240,
      rating: 4.2,
      review_count: 618,
      price_range: "$$$",
      is_active: true,
      default_prep_time_min: 40,
      stripe_account_id: null,
      image_url: null,
      created_at: "",
      is_open: isLunchOrDinner,
      hours: mockHours(),
    },
    {
      id: "r14",
      slug: "bao",
      name: "BAO",
      description:
        "Cantonese dim sum and traditional Chinese dishes on Broadway. Handmade dumplings and classic favorites.",
      cuisine_tags: ["Chinese", "Dim Sum"],
      address: "2050 Broadway",
      city: "Redwood City",
      state: "CA",
      zip: "94063",
      phone: "(650) 780-8806",
      lat: 37.4879,
      lng: -122.2297,
      rating: 4.0,
      review_count: 208,
      price_range: "$$",
      is_active: true,
      default_prep_time_min: 20,
      stripe_account_id: null,
      image_url: null,
      created_at: "",
      is_open: isLunchOrDinner,
      hours: mockHours(),
    },
    {
      id: "r15",
      slug: "limon",
      name: "Limon",
      description:
        "Peruvian cuisine featuring ceviche, rotisserie chicken, and traditional dishes from Peru.",
      cuisine_tags: ["Peruvian"],
      address: "885 Middlefield Road",
      city: "Redwood City",
      state: "CA",
      zip: "94063",
      phone: "(650) 365-9090",
      lat: 37.4816,
      lng: -122.2322,
      rating: 4.0,
      review_count: 226,
      price_range: "$$",
      is_active: true,
      default_prep_time_min: 25,
      stripe_account_id: null,
      image_url: null,
      created_at: "",
      is_open: isLunchOrDinner,
      hours: mockHours(),
    },
  ];
}

// Mock menu data for individual restaurant pages
export function getMockMenu(slug: string): MenuCategoryWithItems[] {
  const menus: Record<string, MenuCategoryWithItems[]> = {
    "la-viga": [
      {
        id: "cat1",
        restaurant_id: "r1",
        name: "Appetizers",
        description: null,
        sort_order: 0,
        is_available: true,
        items: [
          {
            id: "i1",
            restaurant_id: "r1",
            category_id: "cat1",
            name: "Guacamole",
            description:
              "Ripe avocado, onions, cilantro, serrano, tomato, lime juice, queso fresco, totopos & chile de arbol sauce",
            price: 800,
            image_url: null,
            is_available: true,
            sort_order: 0,
            modifier_groups: [],
          },
          {
            id: "i2",
            restaurant_id: "r1",
            category_id: "cat1",
            name: "Sampler Platter",
            description:
              "Empanada de mariscos, crispy coconut prawn, side of fried calamari",
            price: 1900,
            image_url: null,
            is_available: true,
            sort_order: 1,
            modifier_groups: [],
          },
          {
            id: "i3",
            restaurant_id: "r1",
            category_id: "cat1",
            name: "Sauteed Octopus",
            description:
              "Octopus, calamari, chorizo, fennel with chile arbol sauce, served over toasted bread and black bean spread",
            price: 1200,
            image_url: null,
            is_available: true,
            sort_order: 2,
            modifier_groups: [],
          },
        ],
      },
      {
        id: "cat2",
        restaurant_id: "r1",
        name: "Tacos",
        description: null,
        sort_order: 1,
        is_available: true,
        items: [
          {
            id: "i4",
            restaurant_id: "r1",
            category_id: "cat2",
            name: "Tacos (3)",
            description: "Homemade corn tortillas with your choice of protein",
            price: 1500,
            image_url: null,
            is_available: true,
            sort_order: 0,
            modifier_groups: [
              {
                id: "mg1",
                menu_item_id: "i4",
                name: "Choose Protein",
                is_required: true,
                min_selections: 1,
                max_selections: 1,
                sort_order: 0,
                options: [
                  { id: "mo1", modifier_group_id: "mg1", name: "Asada", price_delta: 0, is_available: true, sort_order: 0 },
                  { id: "mo2", modifier_group_id: "mg1", name: "Cochinita", price_delta: 0, is_available: true, sort_order: 1 },
                  { id: "mo3", modifier_group_id: "mg1", name: "Pollo", price_delta: 0, is_available: true, sort_order: 2 },
                  { id: "mo4", modifier_group_id: "mg1", name: "Camaron", price_delta: 200, is_available: true, sort_order: 3 },
                  { id: "mo5", modifier_group_id: "mg1", name: "Pescado", price_delta: 200, is_available: true, sort_order: 4 },
                  { id: "mo6", modifier_group_id: "mg1", name: "Salmon", price_delta: 400, is_available: true, sort_order: 5 },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "cat3",
        restaurant_id: "r1",
        name: "Enchiladas",
        description: null,
        sort_order: 2,
        is_available: true,
        items: [
          {
            id: "i5",
            restaurant_id: "r1",
            category_id: "cat3",
            name: "Veggie Enchiladas",
            description:
              "2 homemade tortillas, guajillo enchilada sauce, queso fresco, cream, cheese, rice & black bean puree",
            price: 1800,
            image_url: null,
            is_available: true,
            sort_order: 0,
            modifier_groups: [],
          },
          {
            id: "i6",
            restaurant_id: "r1",
            category_id: "cat3",
            name: "Steak Enchiladas",
            description: "Same preparation with steak",
            price: 2500,
            image_url: null,
            is_available: true,
            sort_order: 1,
            modifier_groups: [],
          },
          {
            id: "i7",
            restaurant_id: "r1",
            category_id: "cat3",
            name: "Shrimp Enchiladas",
            description: "Same preparation with shrimp",
            price: 2700,
            image_url: null,
            is_available: true,
            sort_order: 2,
            modifier_groups: [],
          },
          {
            id: "i8",
            restaurant_id: "r1",
            category_id: "cat3",
            name: "Seafood Enchiladas",
            description: "Same preparation with mixed seafood",
            price: 2900,
            image_url: null,
            is_available: true,
            sort_order: 3,
            modifier_groups: [],
          },
        ],
      },
      {
        id: "cat4",
        restaurant_id: "r1",
        name: "Entrees",
        description: null,
        sort_order: 3,
        is_available: true,
        items: [
          {
            id: "i9",
            restaurant_id: "r1",
            category_id: "cat4",
            name: "Grilled Skirt Steak",
            description:
              "With poblano garlic mashed potatoes, brussels sprouts, chimichurri sauce",
            price: 3000,
            image_url: null,
            is_available: true,
            sort_order: 0,
            modifier_groups: [],
          },
          {
            id: "i10",
            restaurant_id: "r1",
            category_id: "cat4",
            name: "Blackened Atlantic Salmon",
            description: "Salmon filet with butternut squash",
            price: 2900,
            image_url: null,
            is_available: true,
            sort_order: 1,
            modifier_groups: [],
          },
          {
            id: "i11",
            restaurant_id: "r1",
            category_id: "cat4",
            name: "Grilled Wild Mahi-Mahi",
            description: "Mahi-mahi fillet",
            price: 3000,
            image_url: null,
            is_available: true,
            sort_order: 2,
            modifier_groups: [],
          },
        ],
      },
    ],
    mazra: [
      {
        id: "cat10",
        restaurant_id: "r2",
        name: "Appetizers / Mezza",
        description: null,
        sort_order: 0,
        is_available: true,
        items: [
          {
            id: "i20",
            restaurant_id: "r2",
            category_id: "cat10",
            name: "Heirloom Cauliflower",
            description: "With lemon tahini dressing",
            price: 1400,
            image_url: null,
            is_available: true,
            sort_order: 0,
            modifier_groups: [],
          },
          {
            id: "i21",
            restaurant_id: "r2",
            category_id: "cat10",
            name: "Falafel",
            description:
              "Freshly ground chickpeas, herbs & spices; served with hot sauce & tahini",
            price: 1200,
            image_url: null,
            is_available: true,
            sort_order: 1,
            modifier_groups: [],
          },
          {
            id: "i22",
            restaurant_id: "r2",
            category_id: "cat10",
            name: "Halloumi Rolls",
            description:
              "Halloumi cheese wrapped in phyllo pastry dough, served with spiced honey",
            price: 1400,
            image_url: null,
            is_available: true,
            sort_order: 2,
            modifier_groups: [],
          },
        ],
      },
      {
        id: "cat11",
        restaurant_id: "r2",
        name: "Wraps",
        description: null,
        sort_order: 1,
        is_available: true,
        items: [
          {
            id: "i23",
            restaurant_id: "r2",
            category_id: "cat11",
            name: "Chicken Shawarma Wrap",
            description: "With tzatziki, tomato, onions, pickles & fries",
            price: 1600,
            image_url: null,
            is_available: true,
            sort_order: 0,
            modifier_groups: [],
          },
        ],
      },
      {
        id: "cat12",
        restaurant_id: "r2",
        name: "Plates",
        description: null,
        sort_order: 2,
        is_available: true,
        items: [
          {
            id: "i24",
            restaurant_id: "r2",
            category_id: "cat12",
            name: "Chicken Shawarma Plate",
            description:
              "Crispy thin slices of chicken with basmati rice, hot sauce, garlic toum sauce, pita bread & 2 sides",
            price: 2400,
            image_url: null,
            is_available: true,
            sort_order: 0,
            modifier_groups: [],
          },
          {
            id: "i25",
            restaurant_id: "r2",
            category_id: "cat12",
            name: "Double Kebab Plate",
            description: "Beef and lamb kebab (signature)",
            price: 2800,
            image_url: null,
            is_available: true,
            sort_order: 1,
            modifier_groups: [],
          },
          {
            id: "i26",
            restaurant_id: "r2",
            category_id: "cat12",
            name: "Grilled Salmon Plate",
            description: "Grilled salmon with basmati rice and sides",
            price: 3500,
            image_url: null,
            is_available: true,
            sort_order: 2,
            modifier_groups: [],
          },
        ],
      },
      {
        id: "cat13",
        restaurant_id: "r2",
        name: "Beverages",
        description: null,
        sort_order: 3,
        is_available: true,
        items: [
          {
            id: "i27",
            restaurant_id: "r2",
            category_id: "cat13",
            name: "Mint Lemonade",
            description: "Refreshing house-made mint lemonade",
            price: 600,
            image_url: null,
            is_available: true,
            sort_order: 0,
            modifier_groups: [],
          },
        ],
      },
    ],
    vesta: [
      {
        id: "cat20",
        restaurant_id: "r4",
        name: "Small Plates",
        description: null,
        sort_order: 0,
        is_available: true,
        items: [
          {
            id: "i40",
            restaurant_id: "r4",
            category_id: "cat20",
            name: "Grilled Carrots",
            description: "Cilantro, paprika, cumin, garlic, lemon yogurt",
            price: 1000,
            image_url: null,
            is_available: true,
            sort_order: 0,
            modifier_groups: [],
          },
          {
            id: "i41",
            restaurant_id: "r4",
            category_id: "cat20",
            name: "Burrata Plate",
            description: "Fresh burrata, fleur de sel, grilled bread",
            price: 1300,
            image_url: null,
            is_available: true,
            sort_order: 1,
            modifier_groups: [],
          },
          {
            id: "i42",
            restaurant_id: "r4",
            category_id: "cat20",
            name: "Pork Meatballs",
            description:
              "Arugula, jalapeno aioli, parmigiano reggiano",
            price: 1400,
            image_url: null,
            is_available: true,
            sort_order: 2,
            modifier_groups: [],
          },
          {
            id: "i43",
            restaurant_id: "r4",
            category_id: "cat20",
            name: "Charcuterie",
            description:
              "Salame rosa, soppressata, prosciutto americano, marinated olives",
            price: 1600,
            image_url: null,
            is_available: true,
            sort_order: 3,
            modifier_groups: [],
          },
        ],
      },
      {
        id: "cat21",
        restaurant_id: "r4",
        name: "Red Pies",
        description: null,
        sort_order: 1,
        is_available: true,
        items: [
          {
            id: "i44",
            restaurant_id: "r4",
            category_id: "cat21",
            name: "Margherita",
            description: "Tomato sauce, fresh mozzarella, basil, olive oil",
            price: 2100,
            image_url: null,
            is_available: true,
            sort_order: 0,
            modifier_groups: [],
          },
          {
            id: "i45",
            restaurant_id: "r4",
            category_id: "cat21",
            name: "Pepperoni",
            description:
              "Tomato sauce, pepperoni, fresh mozzarella, calabrian chili honey",
            price: 2700,
            image_url: null,
            is_available: true,
            sort_order: 1,
            modifier_groups: [],
          },
          {
            id: "i46",
            restaurant_id: "r4",
            category_id: "cat21",
            name: "Sausage & Honey",
            description:
              "Spicy Italian sausage, mascarpone, honey, serrano chili (SIGNATURE)",
            price: 2700,
            image_url: null,
            is_available: true,
            sort_order: 2,
            modifier_groups: [],
          },
        ],
      },
      {
        id: "cat22",
        restaurant_id: "r4",
        name: "White Pies",
        description: null,
        sort_order: 2,
        is_available: true,
        items: [
          {
            id: "i47",
            restaurant_id: "r4",
            category_id: "cat22",
            name: "Carbonara",
            description:
              "Mascarpone, pecorino, farm egg, applewood smoked bacon",
            price: 2300,
            image_url: null,
            is_available: true,
            sort_order: 0,
            modifier_groups: [],
          },
        ],
      },
      {
        id: "cat23",
        restaurant_id: "r4",
        name: "Desserts",
        description: null,
        sort_order: 3,
        is_available: true,
        items: [
          {
            id: "i48",
            restaurant_id: "r4",
            category_id: "cat23",
            name: "Mexican Chocolate Bread Pudding",
            description: "Rich chocolate bread pudding",
            price: 1000,
            image_url: null,
            is_available: true,
            sort_order: 0,
            modifier_groups: [],
          },
          {
            id: "i49",
            restaurant_id: "r4",
            category_id: "cat23",
            name: "Basque Cheesecake",
            description: "Burnt Basque-style cheesecake",
            price: 1300,
            image_url: null,
            is_available: true,
            sort_order: 1,
            modifier_groups: [],
          },
        ],
      },
    ],
  };

  return menus[slug] || generateGenericMenu(slug);
}

function generateGenericMenu(slug: string): MenuCategoryWithItems[] {
  const restaurant = getMockRestaurants().find((r) => r.slug === slug);
  if (!restaurant) return [];

  return [
    {
      id: `cat-${slug}-1`,
      restaurant_id: restaurant.id,
      name: "Popular Items",
      description: null,
      sort_order: 0,
      is_available: true,
      items: [
        {
          id: `${slug}-item-1`,
          restaurant_id: restaurant.id,
          category_id: `cat-${slug}-1`,
          name: "House Special",
          description: `${restaurant.name}'s signature dish`,
          price: 2200,
          image_url: null,
          is_available: true,
          sort_order: 0,
          modifier_groups: [],
        },
        {
          id: `${slug}-item-2`,
          restaurant_id: restaurant.id,
          category_id: `cat-${slug}-1`,
          name: "Chef's Selection",
          description: "Ask about today's special preparation",
          price: 2800,
          image_url: null,
          is_available: true,
          sort_order: 1,
          modifier_groups: [],
        },
        {
          id: `${slug}-item-3`,
          restaurant_id: restaurant.id,
          category_id: `cat-${slug}-1`,
          name: "Appetizer Sampler",
          description: "A selection of our favorite starters",
          price: 1600,
          image_url: null,
          is_available: true,
          sort_order: 2,
          modifier_groups: [],
        },
      ],
    },
  ];
}
